name: 'Python Cached Dependencies Action'
description: 'A GitHub Action to cache Python dependencies'
inputs:
  dependencies:
    description: 'Extra dependencies to install for the workflow'
    required: false
    default: ''
runs:
  using: 'composite'
  steps:
    - uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - run: python -m pip install --upgrade pip ${{ inputs.dependencies }} 
      shell: bash