name: Deploy Python Application

on:
  push:
    branches:
      - master
      - dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: pytest

  #    - name: Deploy to Cloud Functions
  #      run: |
  #        gcloud functions deploy your-function-name \
  #        --runtime python38 \
  #        --trigger-http \
  #        --allow-unauthenticated \
  #        --entry-point index \
  #        --source .