name: Release Process
on:
  pull_request:
    branches: [master]
    types: [closed]
  push:
    branches: [master]  
  workflow_dispatch:

jobs:
  semantic-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up and install Python
        uses: ./.github/actions/cached-deps
        with:
          dependencies: 'build twine bump2version wheel'

      - name: Extract repository name
        run: |
          REPO_NAME=$(echo "${{ github.repository }}" | cut -d'/' -f2)
          echo "REPO_NAME=${REPO_NAME}" >> $GITHUB_ENV 
#####
      - name: Semantic Release Custom Action
        id: semantic-release
        uses: MitVo/semantic-release-python@master
        env:
          REPO_NAME: ${{ env.REPO_NAME }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Tag generated
        run: echo "RELEASE_TAG=${{ steps.semantic-release.outputs.release_version }}" >> $GITHUB_ENV
#####
  Publish:
    environment: testing
    runs-on: ubuntu-latest
    needs: semantic-release
    permissions:
      contents: write
      ## IMPORTANT: this permission is mandatory for Trusted Publishing
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up and install Python
        uses: ./.github/actions/cached-deps
        with:
          dependencies: 'build twine bump2version wheel'

      - name: Publish
        run: |
          python -m build
          twine upload dist/* --repository-url https://upload.pypi.org/legacy/ --verbose
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
